= spring-cloud-sample

A collection of RESTful services tied together using Spring Cloud. 

This project is meant to serve as a showcase of Spring technologies like Cloud, Security, OAuth2 and Data Rest. 

[NOTE]
For simplicity, these applications use embedded hsqldb datasources. For this reason, oauth2 security will NOT work unless 
a different database connection is configured (ie. Hsqldb Server, Oracle, MySQL, SQL Server).

You may run these applications in one of two ways: 

. Run each application using the embedded tomcat server.
. Deploy the wars into two tomcat instances. One running the Gateway and Discovery apps, and the second running the other microservices.

IMPORTANT: Please note that the Tomcat ports *MUST* match the ports on each application's `application.yml` file.

== Prerequisites 

*Java 8* - Some components use Java 8 features like LocalDate and lambdas.

*Lombok* - To run this code from eclipse, you'll need to install https://projectlombok.org/[Lombok].  

*Tomcat* - If you prefer not to use the embedded Tomcat, you will need to download https://tomcat.apache.org/download-80.cgi[Tomcat] 
and run two separate instances. One on port 8080 and another on port 8081.

== Gateway Service

To access services through the gateway, you must specify the service name and the URI (including root context path) 
in the form http://hostname:port/{gateway-context}/{service-id}/{service-context}/{resource-uri} 

For example, to call /uaa/token through the gateway, the url would be +
http://localhost:8080/api/uaa-service/uaa/oauth/token?grant_type=password&username=elvis&password=password

== Oauth2 Service

Simple implementation of an Oauth2 server using Spring Security Oauth2 and JDBC token store using HSQLDB. 

Usage: +
```ruby 
curl -X POST -H "Authorization: Basic ZWx2aXM6bm92b2E=" "http://localhost:8082/uaa/oauth/token?grant_type=password&username=elvis&password=password"
```

Where client id is 'elvis' and client secret is 'novoa'.

== Frontend Customer Service

Provides access to CRUD operations for a Customer entity on a database using Spring Data Rest.

Usage: +
*Get Customer list* +
```ruby
curl "http://localhost:8083/frontend-customers/customers/"
``` 
*Add Customer* +
```ruby
curl -X POST -H "Content-Type: application/json" 
-d '{ +
   "firstName": "Frodo", 
   "lastName": "Baggins", 
   "dateOfBirth": "2016-03-29" 
}' "http://localhost:8083/frontend-customers/customers"
```

== License
This project is Open Source software released under the
http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].