spring:
  profiles:
    active: cloud-enabled # enable cloud registration
  datasource:
    platform: hsqldb # Enable In-Memory database  

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/discovery/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 8082
  context-path: /uaa
  
---

spring:
    profiles: tomcat 
    
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/discovery/eureka/
server:
  port: 8081