# Configure this Discovery Server
eureka:
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8081/discovery/eureka/

server:
  port: 8081   # HTTP port
  context-path: /discovery
  
---

spring:
    profiles: tomcat 
    
# Configure this Discovery Server
eureka:
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8080/discovery/eureka/