server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/



#server:
#  port: 8081   # HTTP port
#  context-path: /discovery

spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false